export const BREAKPOINT_NAME = {
  MOBILE: "MOBILE",
  TABLET: "TABLET",
  DESKTOP: "DESKTOP",
  FULLHD: "FULLHD",
} as const

export type BreakpointName = (typeof BREAKPOINT_NAME)[keyof typeof BREAKPOINT_NAME]

export const BREAKPOINT_WIDTH = {
  MOBILE: 375,
  TABLET: 768,
  DESKTOP: 1200,
  FULLHD: 1920,
} as const

export type BreakpointWidth = (typeof BREAKPOINT_WIDTH)[keyof typeof BREAKPOINT_WIDTH]

export const BreakpointWidthToName: Record<BreakpointWidth, BreakpointName> = {
  [BREAKPOINT_WIDTH.MOBILE]: BREAKPOINT_NAME.MOBILE,
  [BREAKPOINT_WIDTH.TABLET]: BREAKPOINT_NAME.TABLET,
  [BREAKPOINT_WIDTH.DESKTOP]: BREAKPOINT_NAME.DESKTOP,
  [BREAKPOINT_WIDTH.FULLHD]: BREAKPOINT_NAME.FULLHD,
}
